name: Python package

on:
  workflow_dispatch:

jobs:
  etapa-python:
    name: Python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: pruebas de texto
        run: python -c "print('Mensaje desde actions')"

  etapa-java:
    name: Java package
    runs-on: ubuntu-latest
    needs: etapa-python
    steps:
      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Verificar versión de Java
        run: |
          python -c "print('Java version:')"
          java -version

      - name: Verificar versión de Maven
        run: |
          python -c "print('Maven version:')"
          mvn -v

  composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: JoelSilvi/composite/.github/actions/new-prueba@main
        with:
          mensaje: "Este es un mensaje personalizado"
