name: Python package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: pruebas de texto
        run: python -c "print('Mensaje desde actions')"
      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Verificar versión de Java
        run: |
          python -c "print('Java version')"
          java -version
